name: Pull Shark Automation

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *" # Run every minute

jobs:
  update-progress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Create Temporary Branch
        run: git checkout -b update-branch

      - name: Execute Python script
        run: python pull-shark-automation.py

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update progress
          title: Update progress
          branch: main

      - name: Merge Pull Request
        if: ${{ steps.create_pr.outputs.pull-request-created == 'true' }}
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const pull_number = context.payload.number;
            const repository = context.repo;
            await github.rest.pulls.merge({
              owner: repository.owner,
              pull_number: pull_number,
              repo: repository.repo
            });
